package recordrangers.services;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Encrypt {

    public static String getHash(String input) throws NoSuchAlgorithmException {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hash = md.digest(input.getBytes(StandardCharsets.UTF_8));
        BigInteger number = new BigInteger(1, hash);

        StringBuilder hexString = new StringBuilder(number.toString(16));

        while (hexString.length() < 64) {
            hexString.insert(0, '0');
        }

        return hexString.toString();
    }

    public static void main(String[] args) {
        try {
            System.out.println("HashCode Generated by SHA-256 for:");
            String s1 = "superSecurePassword";
            System.out.print("\n" + s1 + " is hashed to: " + getHash(s1));
        } catch (NoSuchAlgorithmException e) {
            System.out.println("Error thrown for incorrect algorithm: " + e.getMessage());
        }
    }
}

