name: Java CI with Maven

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
  pull_request:
    branches:
      - main  # Runs on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu VM
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Gets the code from your repo
      
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Eclipse Temurin JDK
          java-version: '19'
          cache: 'maven'  # Caches Maven dependencies for faster builds
      
      - name: Build with Maven
        run: mvn test --file pom.xml  # Runs the Maven build
