name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      database:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: UniversityDB
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=3
        volumes:
          - ./vaadin_project/db/init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
    - uses: actions/checkout@v4
      with:
        # Add this to ensure clean checkout and handle permission issues
        clean: true
    
    # Instead of fixing permissions manually, use proper volume mounting
    - name: Set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file vaadin_project/pom.xml
